name: Feature Request
description: Suggest an idea for valor
title: "ENH: "
labels: [Enhancement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality to valor
        - label: >
            Changing existing functionality in valor
        - label: >
            Removing existing functionality in valor
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve, e.g. "I wish I could use valor to ..."
      placeholder: >
        I wish I could use valor to return evaluations for my top-ranked model.
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using psudocode if relevant.
      placeholder: >
        Add a new backend function that returns evaluations for the top N models.

        def get_ranked_evaluations(..., top_n = None):
            """
            Parameters
            ----------
            ...

            top_n : int, default -1
                Returns only the top N evaluations, ranked according to some user-specified conditions.
            """
            ...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please provide any relevant GitHub issues, code examples or references that help describe and support
        the feature request.
