{{- if .Values.enablePersistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "velour-chart.fullname" . }}-persistent-volume-claim
  labels:
    {{- include "velour-chart.labels" . | nindent 4 }}
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
{{- end }}

---
{{- if .Values.enablePersistence }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "velour-chart.fullname" . }}-persistent-volume
  labels:
    {{- include "velour-chart.labels" . | nindent 4 }}
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
{{- end }}
