apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "velour-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-persistent-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "velour-chart.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 6379
  selector:
    app: {{ .Release.Name }}-redis

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: velour-redis-connection
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-api
    ports:
    - protocol: TCP
      port: 6379