apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
  selector:
    app: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    app: {{ .Release.Name }}