import pandas as pd
from valor_core.classification import evaluate_classification


def test_evaluate_image_clf():
    groundtruth_df = [
        {
            "id": 9052,
            "annotation_id": 11394,
            "label_id": 8071,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.517175"),
            "dataset_name": "test_dataset",
            "label_key": "k4",
            "label_value": "v4",
            "datum_id": 833,
            "datum_uid": "uid6",
        },
        {
            "id": 9050,
            "annotation_id": 11393,
            "label_id": 8071,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.467651"),
            "dataset_name": "test_dataset",
            "label_key": "k4",
            "label_value": "v4",
            "datum_id": 832,
            "datum_uid": "uid5",
        },
        {
            "id": 9051,
            "annotation_id": 11393,
            "label_id": 8072,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.467651"),
            "dataset_name": "test_dataset",
            "label_key": "k5",
            "label_value": "v5",
            "datum_id": 832,
            "datum_uid": "uid5",
        },
        {
            "id": 9053,
            "annotation_id": 11395,
            "label_id": 8074,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.577011"),
            "dataset_name": "test_dataset",
            "label_key": "k3",
            "label_value": "v3",
            "datum_id": 834,
            "datum_uid": "uid8",
        },
    ]

    prediction_df = [
        {
            "id": 4627,
            "annotation_id": 11398,
            "label_id": 8080,
            "score": 1.0,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.894764"),
            "dataset_name": "test_dataset",
            "label_key": "k3",
            "label_value": "v1",
            "datum_id": 834,
            "datum_uid": "uid8",
        },
        {
            "id": 4622,
            "annotation_id": 11396,
            "label_id": 8077,
            "score": 0.47,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.767704"),
            "dataset_name": "test_dataset",
            "label_key": "k4",
            "label_value": "v1",
            "datum_id": 832,
            "datum_uid": "uid5",
        },
        {
            "id": 4623,
            "annotation_id": 11396,
            "label_id": 8076,
            "score": 0.53,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.767704"),
            "dataset_name": "test_dataset",
            "label_key": "k4",
            "label_value": "v8",
            "datum_id": 832,
            "datum_uid": "uid5",
        },
        {
            "id": 4624,
            "annotation_id": 11396,
            "label_id": 8075,
            "score": 1.0,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.767704"),
            "dataset_name": "test_dataset",
            "label_key": "k5",
            "label_value": "v1",
            "datum_id": 832,
            "datum_uid": "uid5",
        },
        {
            "id": 4625,
            "annotation_id": 11397,
            "label_id": 8071,
            "score": 0.71,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.819552"),
            "dataset_name": "test_dataset",
            "label_key": "k4",
            "label_value": "v4",
            "datum_id": 833,
            "datum_uid": "uid6",
        },
        {
            "id": 4626,
            "annotation_id": 11397,
            "label_id": 8079,
            "score": 0.29,
            "created_at": pd.Timestamp("2024-07-29 16:01:29.819552"),
            "dataset_name": "test_dataset",
            "label_key": "k4",
            "label_value": "v5",
            "datum_id": 833,
            "datum_uid": "uid6",
        },
    ]

    eval_ = evaluate_classification(
        groundtruth_df=pd.DataFrame(groundtruth_df),
        prediction_df=pd.DataFrame(prediction_df),
    )

    assert True == False


def test_evaluate_tabular_clf():
    groundtruth_df = [
        {
            "id": 9040,
            "annotation_id": 11373,
            "label_id": 8031,
            "created_at": 1722267392923,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "1",
            "datum_id": 822,
            "datum_uid": "uid0",
        },
        {
            "id": 9041,
            "annotation_id": 11374,
            "label_id": 8031,
            "created_at": 1722267392967,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "1",
            "datum_id": 823,
            "datum_uid": "uid1",
        },
        {
            "id": 9042,
            "annotation_id": 11375,
            "label_id": 8033,
            "created_at": 1722267393007,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "2",
            "datum_id": 824,
            "datum_uid": "uid2",
        },
        {
            "id": 9043,
            "annotation_id": 11376,
            "label_id": 8034,
            "created_at": 1722267393047,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "0",
            "datum_id": 825,
            "datum_uid": "uid3",
        },
        {
            "id": 9044,
            "annotation_id": 11377,
            "label_id": 8034,
            "created_at": 1722267393088,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "0",
            "datum_id": 826,
            "datum_uid": "uid4",
        },
        {
            "id": 9045,
            "annotation_id": 11378,
            "label_id": 8034,
            "created_at": 1722267393125,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "0",
            "datum_id": 827,
            "datum_uid": "uid5",
        },
        {
            "id": 9046,
            "annotation_id": 11379,
            "label_id": 8031,
            "created_at": 1722267393166,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "1",
            "datum_id": 828,
            "datum_uid": "uid6",
        },
        {
            "id": 9047,
            "annotation_id": 11380,
            "label_id": 8031,
            "created_at": 1722267393215,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "1",
            "datum_id": 829,
            "datum_uid": "uid7",
        },
        {
            "id": 9048,
            "annotation_id": 11381,
            "label_id": 8031,
            "created_at": 1722267393263,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "1",
            "datum_id": 830,
            "datum_uid": "uid8",
        },
        {
            "id": 9049,
            "annotation_id": 11382,
            "label_id": 8031,
            "created_at": 1722267393306,
            "dataset_name": "test_dataset",
            "label_key": "class",
            "label_value": "1",
            "datum_id": 831,
            "datum_uid": "uid9",
        },
    ]
    prediction_df = [
        [
            {
                "id": 4600,
                "annotation_id": 11385,
                "label_id": 8033,
                "score": 0.09,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.502504"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 824,
                "datum_uid": "uid2",
            },
            {
                "id": 4599,
                "annotation_id": 11385,
                "label_id": 8031,
                "score": 0.88,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.502504"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 824,
                "datum_uid": "uid2",
            },
            {
                "id": 4598,
                "annotation_id": 11385,
                "label_id": 8034,
                "score": 0.03,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.502504"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 824,
                "datum_uid": "uid2",
            },
            {
                "id": 4603,
                "annotation_id": 11386,
                "label_id": 8033,
                "score": 0.0,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.546293"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 825,
                "datum_uid": "uid3",
            },
            {
                "id": 4602,
                "annotation_id": 11386,
                "label_id": 8031,
                "score": 0.03,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.546293"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 825,
                "datum_uid": "uid3",
            },
            {
                "id": 4601,
                "annotation_id": 11386,
                "label_id": 8034,
                "score": 0.97,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.546293"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 825,
                "datum_uid": "uid3",
            },
            {
                "id": 4606,
                "annotation_id": 11387,
                "label_id": 8033,
                "score": 0.0,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.586264"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 826,
                "datum_uid": "uid4",
            },
            {
                "id": 4605,
                "annotation_id": 11387,
                "label_id": 8031,
                "score": 0.0,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.586264"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 826,
                "datum_uid": "uid4",
            },
            {
                "id": 4604,
                "annotation_id": 11387,
                "label_id": 8034,
                "score": 1.0,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.586264"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 826,
                "datum_uid": "uid4",
            },
            {
                "id": 4609,
                "annotation_id": 11388,
                "label_id": 8033,
                "score": 0.0,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.631094"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 827,
                "datum_uid": "uid5",
            },
            {
                "id": 4608,
                "annotation_id": 11388,
                "label_id": 8031,
                "score": 0.0,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.631094"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 827,
                "datum_uid": "uid5",
            },
            {
                "id": 4607,
                "annotation_id": 11388,
                "label_id": 8034,
                "score": 1.0,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.631094"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 827,
                "datum_uid": "uid5",
            },
            {
                "id": 4612,
                "annotation_id": 11389,
                "label_id": 8033,
                "score": 0.03,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.673800"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 828,
                "datum_uid": "uid6",
            },
            {
                "id": 4611,
                "annotation_id": 11389,
                "label_id": 8031,
                "score": 0.96,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.673800"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 828,
                "datum_uid": "uid6",
            },
            {
                "id": 4610,
                "annotation_id": 11389,
                "label_id": 8034,
                "score": 0.01,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.673800"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 828,
                "datum_uid": "uid6",
            },
            {
                "id": 4615,
                "annotation_id": 11390,
                "label_id": 8033,
                "score": 0.7,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.709818"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 829,
                "datum_uid": "uid7",
            },
            {
                "id": 4614,
                "annotation_id": 11390,
                "label_id": 8031,
                "score": 0.02,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.709818"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 829,
                "datum_uid": "uid7",
            },
            {
                "id": 4613,
                "annotation_id": 11390,
                "label_id": 8034,
                "score": 0.28,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.709818"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 829,
                "datum_uid": "uid7",
            },
            {
                "id": 4618,
                "annotation_id": 11391,
                "label_id": 8033,
                "score": 0.01,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.745536"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 830,
                "datum_uid": "uid8",
            },
            {
                "id": 4617,
                "annotation_id": 11391,
                "label_id": 8031,
                "score": 0.21,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.745536"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 830,
                "datum_uid": "uid8",
            },
            {
                "id": 4616,
                "annotation_id": 11391,
                "label_id": 8034,
                "score": 0.78,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.745536"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 830,
                "datum_uid": "uid8",
            },
            {
                "id": 4621,
                "annotation_id": 11392,
                "label_id": 8033,
                "score": 0.44,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.797759"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 831,
                "datum_uid": "uid9",
            },
            {
                "id": 4620,
                "annotation_id": 11392,
                "label_id": 8031,
                "score": 0.11,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.797759"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 831,
                "datum_uid": "uid9",
            },
            {
                "id": 4619,
                "annotation_id": 11392,
                "label_id": 8034,
                "score": 0.45,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.797759"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 831,
                "datum_uid": "uid9",
            },
            {
                "id": 4594,
                "annotation_id": 11383,
                "label_id": 8033,
                "score": 0.28,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.411278"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 822,
                "datum_uid": "uid0",
            },
            {
                "id": 4593,
                "annotation_id": 11383,
                "label_id": 8031,
                "score": 0.35,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.411278"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 822,
                "datum_uid": "uid0",
            },
            {
                "id": 4592,
                "annotation_id": 11383,
                "label_id": 8034,
                "score": 0.37,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.411278"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 822,
                "datum_uid": "uid0",
            },
            {
                "id": 4597,
                "annotation_id": 11384,
                "label_id": 8033,
                "score": 0.15,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.465625"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "2",
                "datum_id": 823,
                "datum_uid": "uid1",
            },
            {
                "id": 4596,
                "annotation_id": 11384,
                "label_id": 8031,
                "score": 0.61,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.465625"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "1",
                "datum_id": 823,
                "datum_uid": "uid1",
            },
            {
                "id": 4595,
                "annotation_id": 11384,
                "label_id": 8034,
                "score": 0.24,
                "created_at": pd.Timestamp("2024-07-29 15:36:33.465625"),
                "dataset_name": "test_dataset",
                "label_key": "class",
                "label_value": "0",
                "datum_id": 823,
                "datum_uid": "uid1",
            },
        ]
    ]
