name: Run valor-lite code coverage report

on:
  push:
    branches: "**"

permissions:
  id-token: write
  contents: read

jobs:
  lite-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: run object detection tests and report coverage
        run: |
          pip install -e ".[test]"
          COVERAGE_FILE=.coverage.detection python -m coverage run --omit "tests/*"  -m pytest -v tests/detection
          python -m coverage combine
          python -m coverage report -m
          python -m coverage json
          export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV
          if (( $TOTAL < 90 )); then
            echo "Coverage is below 90%"
            exit 1
          fi
        working-directory: ./lite
